import { requireUser } from "@/lib/auth";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { createGithubRepository, getStoredGithubToken, upsertGithubFile } from "@/lib/github";

function repoName(name:string){
  return name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"sk-builder-app";
}

export async function POST(_request:Request, context:{params:Promise<{id:string}>}){
  try{
    const user=await requireUser();
    const {id}=await context.params;
    const s=createServerSupabaseClient();
    const {data:project}=await s.from("projects").select("*").eq("id",id).eq("owner_clerk_user_id",user.id).maybeSingle();
    if(!project)return Response.json({error:"PROJECT_NOT_FOUND"},{status:404});
    const {data:connection}=await s.from("github_connections").select("encrypted_access_token").eq("clerk_user_id",user.id).maybeSingle();
    if(!connection?.encrypted_access_token)return Response.json({error:"GITHUB_NOT_CONNECTED"},{status:400});
    const token=await getStoredGithubToken(connection.encrypted_access_token);
    const {data:files}=await s.from("project_files").select("path,content").eq("project_id",id).eq("status","generated").order("path");
    if(!files?.length)return Response.json({error:"BUILD_REQUIRED"},{status:400});
    let fullName=project.github_repo_full_name as string|undefined;
    let url=project.github_repo_url as string|undefined;
    if(!fullName){
      const created=await createGithubRepository(token,repoName(project.name),project.description||"Generated by SK Builder");
      fullName=created.full_name; url=created.html_url;
      await s.from("projects").update({github_repo_full_name:fullName,github_repo_url:url}).eq("id",id);
    }
    for(const file of files){
      if(typeof file.content==="string"&&!file.path.includes("..")&&!file.path.startsWith("/")&&!file.path.includes(".env")){
        await upsertGithubFile(token,fullName,file.path,file.content,"SK Builder: sync "+file.path);
      }
    }
    await s.from("build_logs").insert({project_id:id,clerk_user_id:user.id,level:"info",message:"Workspace files synced to GitHub."});
    return Response.json({ok:true,repository:{full_name:fullName,url}});
  }catch(error){
    return Response.json({error:error instanceof Error?error.message:"GITHUB_SYNC_FAILED"},{status:500});
  }
}
